image: gitpod/workspace-full:latest

# Set environment variables for the entire workspace
env:
  GITPOD_WORKSPACE_ID: $GITPOD_WORKSPACE_ID

tasks:
  - name: infrastructure
    before: |
      echo 'Bringing down any previously running containers'
    init: |
      cd docker
      docker-compose down -v
  - name: postgres
    init: |
      cd docker
      echo 'Starting postgres container'
      docker-compose up -d postgres
      echo 'Started postgres'
  - name: backend
    init: |
      cd docker
      echo -e  "\nALLOWED_ORIGINS=\"['$(gp url 4000)']\"" >> .env
      echo -e  "\nALLOWED_ORIGINS=\"['$(gp url 4000)']\""
      echo 'Building backend container'
      docker-compose build backend
      echo 'Built backend'
    command: |
      gp await-port 7432
      cd docker
      echo 'Starting backend container'
      docker-compose up -d backend
      echo 'Started backend'
  - name: frontend
    init: |
      cd docker
      echo 'Copying .env-gitpod to .env'
      cp .env-gitpod .env
      eval $(gp env -e)
      # Remove any existing frontend container to ensure clean rebuild
      docker-compose rm -f frontend || true
      # Ensure VITE_API_BASE_URL is set correctly for the build (force HTTPS)
      export VITE_API_BASE_URL="$(gp url 8300 | sed 's/^http:/https:/')"
      # Remove any existing VITE_API_BASE_URL entries and add the correct one
      sed -i '/VITE_API_BASE_URL/d' .env
      echo "VITE_API_BASE_URL=$(gp url 8300 | sed 's/^http:/https:/')" >> .env
      echo "VITE_API_BASE_URL=$(gp url 8300 | sed 's/^http:/https:/')"
      # Verify the environment variable is set correctly
      echo "Raw gp url output: $(gp url 8300)"
      echo "Processed VITE_API_BASE_URL: $(gp url 8300 | sed 's/^http:/https:/')"
      echo "Verifying VITE_API_BASE_URL in .env: $(grep VITE_API_BASE_URL .env)"
      echo "Current VITE_API_BASE_URL: $VITE_API_BASE_URL"
      echo 'Building frontend container'
      # Pass the environment variable explicitly to docker-compose build (force HTTPS)
      echo "Building with VITE_API_BASE_URL: $(gp url 8300 | sed 's/^http:/https:/')"
      VITE_API_BASE_URL="$(gp url 8300 | sed 's/^http:/https:/')" docker-compose build --no-cache frontend
      echo 'Built frontend'
      # Verify the environment variable in the built container
      echo "Verifying environment variable in container..."
      docker-compose run --rm frontend env | grep VITE_API_BASE_URL || echo "VITE_API_BASE_URL not found in container environment"
    command: |
      gp await-port 8300
      eval $(gp env -e)
      export VITE_API_BASE_URL="$(gp url 8300 | sed 's/^http:/https:/')"
      cd docker
      echo 'Starting frontend container'
      docker-compose up -d frontend
      echo 'Started frontend'

ports:
  - name: Frontend
    description: Port 4000 for the frontend
    port: 4000
    onOpen: open-preview
    visibility: public
  - name: Backend
    description: Port 8300 for the backend
    port: 8300
    onOpen: notify
    visibility: public
  - name: postgres
    description: Port 7432 for the postgres
    port: 7432
    onOpen: ignore
