image: gitpod/workspace-full:latest

tasks:
  - name: infrastructure
    before: |
      echo 'Bringing down any previously running containers'
    init: |
      cd docker
      docker-compose down -v
  - name: postgres
    init: |
      cd docker
      echo 'Starting postgres container'
      docker-compose up -d postgres
      echo 'Started postgres'
  - name: backend
    init: |
      cd docker
      # Set ALLOWED_ORIGINS for backend CORS
      echo "ALLOWED_ORIGINS=\"['$(gp url 4000)']\"" >> .env
      echo "ALLOWED_ORIGINS set to: ['$(gp url 4000)']"
      echo 'Building backend container'
      docker-compose build backend
      echo 'Built backend'
    command: |
      gp await-port 7432
      cd docker
      # Ensure ALLOWED_ORIGINS is set for backend CORS
      sed -i '/ALLOWED_ORIGINS/d' .env
      echo "ALLOWED_ORIGINS=\"['$(gp url 4000)']\"" >> .env
      echo "ALLOWED_ORIGINS set to: ['$(gp url 4000)']"
      echo 'Starting backend container'
      docker-compose up -d backend
      echo 'Started backend'
  - name: frontend
    init: |
      cd docker
      echo 'Copying .env-gitpod to .env'
      cp .env-gitpod .env
      eval $(gp env -e)
      # Set VITE_API_BASE_URL for Gitpod environment
      export VITE_API_BASE_URL=$(gp url 8300)
      # Update the .env file with the Gitpod URL
      sed -i '/VITE_API_BASE_URL/d' .env
      echo "VITE_API_BASE_URL=$(gp url 8300)" >> .env
      echo "VITE_API_BASE_URL set to: $(gp url 8300)"
      echo 'Building frontend container'
      docker-compose build frontend
      echo 'Built frontend'
    command: |
      gp await-port 8300
      eval $(gp env -e)
      export VITE_API_BASE_URL=$(gp url 8300)
      # Ensure the .env file has the latest Gitpod URL
      sed -i '/VITE_API_BASE_URL/d' .env
      echo "VITE_API_BASE_URL=$(gp url 8300)" >> .env
      echo "VITE_API_BASE_URL set to: $(gp url 8300)"
      cd docker
      echo 'Starting frontend container'
      docker-compose up -d frontend
      echo 'Started frontend'

ports:
  - name: Frontend
    description: Port 4000 for the frontend
    port: 4000
    onOpen: open-preview
    visibility: public
  - name: Backend
    description: Port 8300 for the backend
    port: 8300
    onOpen: notify
    visibility: public
  - name: postgres
    description: Port 7432 for the postgres
    port: 7432
    onOpen: ignore
