image: gitpod/workspace-full:latest

tasks:
  - name: infrastructure
    before: |
      echo 'Bringing down any previously running containers'
    init: |
      cd deployment/local
      docker-compose down -v
  - name: postgres
    init: |
      cd deployment/local
      echo 'Starting postgres container'
      docker-compose up -d postgres
      echo 'Started postgres'
  - name: backend
    init: |
      cd deployment/local
      echo 'Building backend container'
      docker-compose build backend
      echo 'Built backend'
    command: |
      gp await-port 7432
      cd deployment/local
      echo 'Starting backend container'
      docker-compose up -d backend
      echo 'Started backend'
  - name: frontend
    init: |
      cd deployment/local
      echo 'Copying .env-gitpod to .env'
      cp .env-gitpod .env
      eval $(gp env -e)
      export VITE_API_BASE_URL=$(gp url 8300)
      echo 'Building frontend container'
      docker-compose build frontend
      echo 'Built frontend'
    command: |
      gp await-port 8300
      eval $(gp env -e)
      export VITE_API_BASE_URL=$(gp url 8300)
      cd deployment/local
      echo 'Starting frontend container'
      docker-compose up -d frontend
      echo 'Started frontend'

ports:
  - name: Frontend
    description: Port 4000 for the frontend
    port: 4000
    onOpen: open-preview
    visibility: public
  - name: Backend
    description: Port 8300 for the backend
    port: 8300
    onOpen: ignore
    visibility: public
  - name: postgres
    description: Port 7432 for the postgres
    port: 7432
    onOpen: ignore