services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
    container_name: app-frontend
    # depends_on:
    #   - backend
    env_file:
      - ./.env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
    ports:
      - "${FRONTEND_HTTP_PORT:-8080}:80"
    restart: unless-stopped

networks:
  default:
    name: app-network
